print("Hello Bhavik")
print("Hello World!!!")
print("Hello Developers")
print("Hello Python!!!")
print("Hello Invinsense")
print("We did it!!!!! Bro!!!!")
print("Try and Try will get success")
print("We are the champions")