print("Hello Bhavik")
print("Hello World!!!")
print("Hello Developers")
print("Hello Python!!!")
print("Hello Invinsense")
print("We did it!!!!! Bro!!!!")
print("Try and Try will get success")
print("We are the champions")
print("We are the best")
print("We are the winners")
print("We are the developers")
print("We are the programmers")
print("We are the coders")